version: '3'

vars:
  MODULE: github.com/imedwei/railway-postgres-backup
  BINARY: postgres-backup

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the application
    cmds:
      - go build -o {{.BINARY}} ./cmd/backup

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  mod:
    desc: Download and tidy modules
    cmds:
      - go mod download
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY}}
      - rm -f coverage.out coverage.html

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t railway-postgres-backup:latest .

  docker:run:
    desc: Run Docker container
    cmds:
      - docker run --rm railway-postgres-backup:latest

  dev:
    desc: Run the application locally
    cmds:
      - go run ./cmd/backup

  docker:compose:up:
    desc: Start local development environment
    cmds:
      - docker-compose up -d
      - echo "Waiting for services to be ready..."
      - sleep 10
      - docker-compose exec -T minio mc alias set local http://localhost:9000 minioadmin minioadmin
      - docker-compose exec -T minio mc mb local/backups || true

  docker:compose:down:
    desc: Stop local development environment
    cmds:
      - docker-compose down -v

  docker:compose:test:
    desc: Run backup in docker-compose environment
    cmds:
      - docker-compose run --rm backup